{"mappings":"AAaoBA,YAAT,WACT,IACEC,K,CACA,MAAOC,GACPC,QAAQC,IAAI,S,IAEb,KAEHD,QAAQC,IAAI","sources":["src/js/01-try-catch.js"],"sourcesContent":["// Обработка ошибок с try...catch\n//  - Синтаксис\n//  - Какие ошибки ловит\n//    - ❌ ошибки парсинга (parsing errors)\n//    - ✅ ошибки выполнения (runtime errors)\n//  - Ловит только ошибки в синхронном коде\n//    - Как словить ошибку в асинхронном коде\n//  - Объект ошибки\n//    - name\n//    - message\n//    - stack\n//  - Блок catch без объекта ошибки\n\nsetTimeout(() => {\n  try {\n    myVar;\n  } catch (error) {\n    console.log('Ошибка');\n  }\n}, 1000);\n\nconsole.log('После try... Catch');\n\n// try {\n//   console.log('Внутри try до myVar');\n\n//   myVar;\n\n//   console.log('Внутри try после myVar');\n// } catch (error) {\n//   console.log('Ошибка!');\n// }\n\n// console.log('После try...catch');\n"],"names":["setTimeout","myVar","error","console","log"],"version":3,"file":"01-try-catch.5de6fec8.js.map"}